version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: hms-mysql
    environment:
      MYSQL_DATABASE: hms_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: hmsuser
      MYSQL_PASSWORD: hmspassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: hms-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hms_db
      SPRING_DATASOURCE_USERNAME: hmsuser
      SPRING_DATASOURCE_PASSWORD: hmspassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:


